### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by fgnievinski** [soichisumi/issue-copy-action#20]
greetings! thank you for this tool. can you clarify how to install it, please? 

I've tried simply copying the content of:
https://github.com/marketplace/actions/github-issue-copier#workflowyaml
```
uses: soichisumi/issue-copy-action@v0.2.0
with:
  keyword: "/copy"
  targetRepository: soichisumi/issue-copy-action
  githubToken: ${{ secrets.GITHUB_TOKEN }}
  contentOfNewIssue: 'prefix of newly created issue'
```

then pasting it in my repo `.github/workflow.yml`.

but nothing happens when I enter `/copy` in a issue.

I've also tried copying from:
https://github.com/marketplace/actions/github-issue-copier
```
uses: soichisumi/issue-copy-action@v0.2.0
with:
  keyword: "/copy"
  targetRepository: soichisumi/issue-copy-action
  githubToken: ${{ secrets.GITHUB_TOKEN }}
  contentOfNewIssue: 'prefix of newly created issue'

```  

do I need to install `label-syncer`, too?

is the bot enabled by default?

thanks for your help.
